all:
  children:
    frr_routers:
      hosts:
        router1:
          ansible_host: localhost
          container_name: "frr-router1"
          device_id: 1
        router2:
          ansible_host: localhost  
          container_name: "frr-router2"
          device_id: 2
      vars:
        ansible_connection: local
        ansible_python_interpreter: "{{ ansible_playbook_python }}"